# Generated by Django 3.2.7 on 2021-10-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalNo', models.CharField(blank=True, max_length=120, null=True)),
                ('surname', models.CharField(blank=True, max_length=120, null=True)),
                ('othernames', models.CharField(blank=True, max_length=120, null=True)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('occupation', models.CharField(blank=True, max_length=120, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=120, null=True)),
                ('tribe', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name_plural': 'Patient_info',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(blank=True, max_length=120, null=True)),
                ('rank_name', models.CharField(blank=True, max_length=120, null=True)),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info')),
            ],
            options={
                'verbose_name_plural': 'Rank',
            },
        ),
        migrations.CreateModel(
            name='patient_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info')),
            ],
            options={
                'verbose_name_plural': 'patient_pic',
            },
        ),
        migrations.CreateModel(
            name='Next_of_kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=120, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info')),
            ],
            options={
                'verbose_name_plural': 'Next_of_kin',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_no', models.CharField(blank=True, max_length=120, null=True)),
                ('street_name', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('lga', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info')),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
    ]
