# Generated by Django 3.2.7 on 2021-11-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0002_rename_name_patient_info_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='hospitalNo',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
