# Generated by Django 3.2.7 on 2021-11-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0003_alter_patient_info_hospitalno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
