# Generated by Django 3.2.7 on 2021-11-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0005_alter_next_of_kin_personal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_info',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
