# Generated by Django 3.2.7 on 2021-11-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0007_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info'),
        ),
    ]
