# Generated by Django 3.2.7 on 2021-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0008_auto_20211110_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_pic',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='patients_pic'),
        ),
    ]
